import { useWallet } from '@solana/wallet-adapter-react';
import type { NextPage } from 'next';
import dynamic from 'next/dynamic';
import Head from 'next/head';
import Image from 'next/image';
import React, { useEffect } from 'react';
import styles from '../styles/Home.module.css';
import { Stripe, loadStripe } from "@stripe/stripe-js";

const Home: NextPage = () => {
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    Success! 
                </h1>
                <a>We are currently minting your NFT, please check your wallet in 30 seconds! :)</a>
            </main>
        </div>
    );
};

export default Home;
